apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: "CI Radar — HTML to MinIO"

on:
  workflow_dispatch:
    inputs:
      jenkins_controller_url:
        description: "Jenkins Controller URL (e.g., https://my-controller.cloudbees.com)"
        type: string
        required: true
        default: "https://core.cloudbees.guru/shared-demos/"
      environment_name:
        description: "Environment to use for credentials"
        type: choice
        options:
          - "GURU-ENV"
        default: "GURU-ENV"
      language:
        description: "Report language"
        type: choice
        options: ["en", "fr"]
        default: "en"
      prompt:
        description: "Optional custom prompt (if empty, uses default prompt for selected language)"
        type: string
        required: false

jobs:
  ci-radar:
    environment: ${{ inputs.environment_name }}
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_S3_FORCE_PATH_STYLE: "true"

    steps:
      - name: Checkout CI Radar Repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: lsa26/ci-radar
          token: ${{ secrets.GITHUB_CHECK }}
          ref: main

      - name: Configure Environment
        uses: docker://alpine:latest
        shell: sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          JENKINS_USERNAME: ${{ secrets.GURU-USERNAME }}
          JENKINS_PASSWORD: ${{ secrets.GURU-PASS }}
        run: |
          set -euo pipefail
          
          echo "🔧 Configuring environment..."
          echo "Working directory: $(pwd)"
          echo "Workspace content:"
          ls -la /cloudbees/workspace/ || echo "Workspace not accessible"
          
          # Navigate to workspace
          cd /cloudbees/workspace
          
          echo "Controller URL: ${{ inputs.jenkins_controller_url }}"
          echo "Environment: ${{ inputs.environment_name }}"
          
          # Validate Jenkins URL
          case "${{ inputs.jenkins_controller_url }}" in
            http://*|https://*)
              echo "✅ Valid URL format"
              ;;
            *)
              echo "❌ Error: Jenkins URL must start with http:// or https://"
              exit 1
              ;;
          esac
          
          # Validate credentials
          if [ -z "$JENKINS_USERNAME" ] || [ -z "$JENKINS_PASSWORD" ]; then
            echo "❌ Jenkins credentials not found"
            exit 1
          fi
          
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OpenAI API key not found"
            exit 1
          fi
          
          # Create .env file in workspace
          cat > /cloudbees/workspace/.env << EOF
          JENKINS_URL=${{ inputs.jenkins_controller_url }}
          JENKINS_USERNAME=$JENKINS_USERNAME
          JENKINS_TOKEN=$JENKINS_PASSWORD
          OPENAI_API_KEY=$OPENAI_API_KEY
          AI_MODEL=gpt-4
          EOF
          
          echo "✅ Environment configured successfully"
          echo "📁 Files in workspace:"
          ls -la /cloudbees/workspace/

      - name: Install Dependencies and Run Analysis
        id: run
        uses: docker://python:3.11
        shell: bash
        run: |
          set -euo pipefail
          
          # Navigate to workspace where our code is
          cd /cloudbees/workspace
          
          echo "📦 Installing Python dependencies..."
          python -V
          pip install --upgrade pip --no-cache-dir
          
          if [ ! -f "requirements.txt" ]; then
            echo "❌ requirements.txt not found in $(pwd)"
            echo "Available files:"
            ls -la
            exit 1
          fi
          
          pip install -r requirements.txt --no-cache-dir
          echo "✅ Dependencies installed"
          
          echo ""
          echo "🔍 Starting CI Radar analysis..."
          
          if [ ! -f "main.py" ]; then
            echo "❌ main.py not found in $(pwd)"
            ls -la
            exit 1
          fi
          
          if [ ! -f ".env" ]; then
            echo "❌ .env file not found in $(pwd)"
            ls -la
            exit 1
          fi
          
          mkdir -p outputs
          
          # Build arguments
          args="--format html --language ${{ inputs.language }}"
          
          # Smart prompt selection
          if [ -n "${{ inputs.prompt }}" ]; then
            args="$args --prompt '${{ inputs.prompt }}'"
          else
            if [ "${{ inputs.language }}" = "fr" ]; then
              if [ -f "prompts/prompt_expert_fr.txt" ]; then
                args="$args --prompt prompts/prompt_expert_fr.txt"
              else
                echo "⚠️ French prompt file not found, using default"
              fi
            else
              if [ -f "prompts/prompt_expert_en.txt" ]; then
                args="$args --prompt prompts/prompt_expert_en.txt"
              else
                echo "⚠️ English prompt file not found, using default"
              fi
            fi
          fi
          
          echo "🚀 Running: python main.py $args"
          eval "python main.py $args"

          REPORT_FILE=$(find /cloudbees/workspace/outputs -name "*.html" | head -n1)
          if [ -z "$REPORT_FILE" ]; then
            echo "❌ No HTML report found in /cloudbees/workspace/outputs/"
            echo "Contents of outputs:"
            ls -la /cloudbees/workspace/outputs/ || echo "outputs directory not found"
            exit 1
          fi

          echo "✅ Analysis completed: $REPORT_FILE"
          
          # Store absolute path for next steps
          echo "report-file=$REPORT_FILE" >> "$CLOUDBEES_OUTPUTS"

      - name: Verify Files Before Upload
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "📁 Verifying workspace content before upload..."
          cd /cloudbees/workspace
          
          echo "Workspace content:"
          ls -la /cloudbees/workspace/
          
          echo ""
          echo "Outputs directory:"
          ls -la /cloudbees/workspace/outputs/ || echo "No outputs directory"
          
          echo ""
          echo "HTML files:"
          find /cloudbees/workspace -name "*.html" -type f || echo "No HTML files found"

      - name: Upload to MinIO
        id: minio
        uses: docker://alpine:latest
        shell: sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
        run: |
          set -euo pipefail
          
          echo "☁️ Uploading to MinIO..."
          cd /cloudbees/workspace
          
          # Find the report file using absolute path
          REPORT_FILE=$(find /cloudbees/workspace/outputs -name "*.html" -type f | head -n1)
          if [ -z "$REPORT_FILE" ]; then
            echo "❌ No HTML report found in workspace"
            echo "Workspace structure:"
            find /cloudbees/workspace -type f -name "*.html" || echo "No HTML files anywhere"
            exit 1
          fi
          
          echo "📄 Found report file: $REPORT_FILE"
          
          # Verify file exists and is readable
          if [ ! -f "$REPORT_FILE" ]; then
            echo "❌ Report file does not exist: $REPORT_FILE"
            exit 1
          fi
          
          if [ ! -r "$REPORT_FILE" ]; then
            echo "❌ Report file is not readable: $REPORT_FILE"
            exit 1
          fi
          
          echo "📊 File size: $(wc -c < "$REPORT_FILE") bytes"
          
          # Install AWS CLI
          apk add --no-cache py3-pip
          pip3 install awscli --no-cache-dir
          
          # Create safe filename
          SAFE_CONTROLLER=$(echo "${{ inputs.jenkins_controller_url }}" | sed 's|https\?://||' | sed 's|[^a-zA-Z0-9.-]|-|g')
          KEY="ci-radar/reports/${{ cloudbees.run_id }}-${SAFE_CONTROLLER}-${{ inputs.language }}.html"

          # Upload
          echo "📤 Uploading $REPORT_FILE to s3://${{ vars.S3_BUCKET }}/${KEY}"
          aws s3 cp "$REPORT_FILE" "s3://${{ vars.S3_BUCKET }}/${KEY}" \
            --endpoint-url "$ENDPOINT" \
            --content-type text/html

          # Generate presigned URL (7 days)
          URL=$(aws s3 presign "s3://${{ vars.S3_BUCKET }}/${KEY}" \
            --expires-in 604800 --endpoint-url "$ENDPOINT")

          echo "✅ Upload completed"
          echo ""
          echo "🔗 MinIO URL (valid for 7 days):"
          echo "$URL"
          
          # Output the URL for next steps
          echo "minio-url=$URL" >> "$CLOUDBEES_OUTPUTS"

      - name: Register CI Radar Report Artifact
        id: register-artifact
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: ci-radar-report
          version: ${{ cloudbees.run_id }}-${{ inputs.language }}
          url: ${{ steps.minio.outputs.minio-url }}

      - name: Publish CI Radar Report Artifact
        uses: cloudbees-io/publish-artifact@v2
        with:
          path: outputs/*.html
          name: ci-radar-report-${{ inputs.language }}

      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## 🎯 CI Radar Analysis Report

            **Jenkins Controller:** ${{ inputs.jenkins_controller_url }}
            **Language:** ${{ inputs.language }}

            ### 📊 Report Details
            - **Artifact ID:** ${{ steps.register-artifact.outputs.artifact-id }}
            - **Report Version:** ${{ cloudbees.run_id }}-${{ inputs.language }}
            - **Environment:** ${{ inputs.environment_name }}

            ### 🔗 Access Report
            [📄 View CI Radar Report](${{ steps.minio.outputs.minio-url }})

            > Report is available for 7 days via MinIO presigned URL

            ### ⚙️ Analysis Configuration
            - **Prompt Type:** ${{ inputs.prompt && 'Custom' || 'Default' }}
            - **Target Controller:** ${{ inputs.jenkins_controller_url }}
            - **Run ID:** ${{ cloudbees.run_id }}
          format: MARKDOWN

      - name: Display Results
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo ""
          echo "🎉 CI RADAR ANALYSIS COMPLETED!"
          echo "==============================="
          echo ""
          echo "📊 Details:"
          echo "   Controller: ${{ inputs.jenkins_controller_url }}"
          echo "   Language: ${{ inputs.language }}"
          echo "   Run ID: ${{ cloudbees.run_id }}"
          echo "   Artifact ID: ${{ steps.register-artifact.outputs.artifact-id }}"
          echo ""
          echo "📦 Artifacts Published:"
          echo "   • CloudBees Artifact: ci-radar-report-${{ inputs.language }}"
          echo "   • Registered Artifact: ci-radar-report (v${{ cloudbees.run_id }}-${{ inputs.language }})"
          echo ""
          echo "🔗 MinIO Report URL (valid for 7 days):"
          echo "${{ steps.minio.outputs.minio-url }}"
          echo ""
          echo "✅ Evidence published to CloudBees platform"

    outputs:
      ARTIFACT_ID: ${{ steps.register-artifact.outputs.artifact-id }}
      MINIO_URL: ${{ steps.minio.outputs.minio-url }}